[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "dist"
  node_version = "18"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"

[dev]
  framework = "astro"
  targetPort = 4321
  port = 8888
  publish = "dist"
  autoLaunch = true

# Gestion des routes pour SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité basiques
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache optimisé pour les assets statiques
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"